/*
Tender Management API

API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateBidRequest struct for CreateBidRequest
type CreateBidRequest struct {
	// Полное название предложения
	Name string `json:"name"`
	// Описание предложения
	Description string    `json:"description"`
	Status      BidStatus `json:"status"`
	// Уникальный идентификатор тендера, присвоенный сервером.
	TenderId string `json:"tenderId"`
	// Уникальный идентификатор организации, присвоенный сервером.
	OrganizationId string `json:"organizationId"`
	// Уникальный slug пользователя.
	CreatorUsername string `json:"creatorUsername"`
}

// NewCreateBidRequest instantiates a new CreateBidRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBidRequest(name string, description string, status BidStatus, tenderId string, organizationId string, creatorUsername string) *CreateBidRequest {
	this := CreateBidRequest{}
	this.Name = name
	this.Description = description
	this.Status = status
	this.TenderId = tenderId
	this.OrganizationId = organizationId
	this.CreatorUsername = creatorUsername
	return &this
}

// NewCreateBidRequestWithDefaults instantiates a new CreateBidRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBidRequestWithDefaults() *CreateBidRequest {
	this := CreateBidRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateBidRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateBidRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateBidRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *CreateBidRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateBidRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateBidRequest) SetDescription(v string) {
	o.Description = v
}

// GetStatus returns the Status field value
func (o *CreateBidRequest) GetStatus() BidStatus {
	if o == nil {
		var ret BidStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateBidRequest) GetStatusOk() (*BidStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateBidRequest) SetStatus(v BidStatus) {
	o.Status = v
}

// GetTenderId returns the TenderId field value
func (o *CreateBidRequest) GetTenderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenderId
}

// GetTenderIdOk returns a tuple with the TenderId field value
// and a boolean to check if the value has been set.
func (o *CreateBidRequest) GetTenderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenderId, true
}

// SetTenderId sets field value
func (o *CreateBidRequest) SetTenderId(v string) {
	o.TenderId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *CreateBidRequest) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *CreateBidRequest) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *CreateBidRequest) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetCreatorUsername returns the CreatorUsername field value
func (o *CreateBidRequest) GetCreatorUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatorUsername
}

// GetCreatorUsernameOk returns a tuple with the CreatorUsername field value
// and a boolean to check if the value has been set.
func (o *CreateBidRequest) GetCreatorUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatorUsername, true
}

// SetCreatorUsername sets field value
func (o *CreateBidRequest) SetCreatorUsername(v string) {
	o.CreatorUsername = v
}

func (o CreateBidRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["tenderId"] = o.TenderId
	}
	if true {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if true {
		toSerialize["creatorUsername"] = o.CreatorUsername
	}
	return json.Marshal(toSerialize)
}

type NullableCreateBidRequest struct {
	value *CreateBidRequest
	isSet bool
}

func (v NullableCreateBidRequest) Get() *CreateBidRequest {
	return v.value
}

func (v *NullableCreateBidRequest) Set(val *CreateBidRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBidRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBidRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBidRequest(val *CreateBidRequest) *NullableCreateBidRequest {
	return &NullableCreateBidRequest{value: val, isSet: true}
}

func (v NullableCreateBidRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBidRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
