/*
Tender Management API

API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка). 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// BidAuthorType Тип автора
type BidAuthorType string

// List of bidAuthorType
const (
	ORGANIZATION BidAuthorType = "Organization"
	USER BidAuthorType = "User"
)

// All allowed values of BidAuthorType enum
var AllowedBidAuthorTypeEnumValues = []BidAuthorType{
	"Organization",
	"User",
}

func (v *BidAuthorType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BidAuthorType(value)
	for _, existing := range AllowedBidAuthorTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BidAuthorType", value)
}

// NewBidAuthorTypeFromValue returns a pointer to a valid BidAuthorType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBidAuthorTypeFromValue(v string) (*BidAuthorType, error) {
	ev := BidAuthorType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BidAuthorType: valid values are %v", v, AllowedBidAuthorTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BidAuthorType) IsValid() bool {
	for _, existing := range AllowedBidAuthorTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to bidAuthorType value
func (v BidAuthorType) Ptr() *BidAuthorType {
	return &v
}

type NullableBidAuthorType struct {
	value *BidAuthorType
	isSet bool
}

func (v NullableBidAuthorType) Get() *BidAuthorType {
	return v.value
}

func (v *NullableBidAuthorType) Set(val *BidAuthorType) {
	v.value = val
	v.isSet = true
}

func (v NullableBidAuthorType) IsSet() bool {
	return v.isSet
}

func (v *NullableBidAuthorType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBidAuthorType(val *BidAuthorType) *NullableBidAuthorType {
	return &NullableBidAuthorType{value: val, isSet: true}
}

func (v NullableBidAuthorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBidAuthorType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

