/*
Tender Management API

API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EditBidRequest struct for EditBidRequest
type EditBidRequest struct {
	// Полное название предложения
	Name *string `json:"name,omitempty"`
	// Описание предложения
	Description *string `json:"description,omitempty"`
}

// NewEditBidRequest instantiates a new EditBidRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditBidRequest() *EditBidRequest {
	this := EditBidRequest{}
	return &this
}

// NewEditBidRequestWithDefaults instantiates a new EditBidRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditBidRequestWithDefaults() *EditBidRequest {
	this := EditBidRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EditBidRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditBidRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EditBidRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EditBidRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EditBidRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditBidRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EditBidRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EditBidRequest) SetDescription(v string) {
	o.Description = &v
}

func (o EditBidRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableEditBidRequest struct {
	value *EditBidRequest
	isSet bool
}

func (v NullableEditBidRequest) Get() *EditBidRequest {
	return v.value
}

func (v *NullableEditBidRequest) Set(val *EditBidRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditBidRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditBidRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditBidRequest(val *EditBidRequest) *NullableEditBidRequest {
	return &NullableEditBidRequest{value: val, isSet: true}
}

func (v NullableEditBidRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditBidRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
